package com.atet.tvmarket.entity.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.atet.tvmarket.entity.dao.ActInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ACT_INFO.
*/
public class ActInfoDao extends AbstractDao<ActInfo, String> {

    public static final String TABLENAME = "ACT_INFO";

    /**
     * Properties of entity ActInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property ActivityId = new Property(0, String.class, "activityId", true, "ACTIVITY_ID");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Remark = new Property(2, String.class, "remark", false, "REMARK");
        public final static Property StartTime = new Property(3, Long.class, "startTime", false, "START_TIME");
        public final static Property EndTime = new Property(4, Long.class, "endTime", false, "END_TIME");
        public final static Property Rules = new Property(5, String.class, "rules", false, "RULES");
        public final static Property Prize = new Property(6, String.class, "prize", false, "PRIZE");
        public final static Property Photo = new Property(7, String.class, "photo", false, "PHOTO");
        public final static Property ErectPhoto = new Property(8, String.class, "erectPhoto", false, "ERECT_PHOTO");
        public final static Property SquarePhoto = new Property(9, String.class, "squarePhoto", false, "SQUARE_PHOTO");
        public final static Property Video = new Property(10, String.class, "video", false, "VIDEO");
        public final static Property Thumbnail = new Property(11, String.class, "thumbnail", false, "THUMBNAIL");
        public final static Property Url = new Property(12, String.class, "url", false, "URL");
        public final static Property Recommend = new Property(13, Integer.class, "recommend", false, "RECOMMEND");
        public final static Property GameId = new Property(14, String.class, "gameId", false, "GAME_ID");
        public final static Property PackgeName = new Property(15, String.class, "packgeName", false, "PACKGE_NAME");
        public final static Property Number = new Property(16, Integer.class, "number", false, "NUMBER");
        public final static Property CreateTime = new Property(17, Long.class, "createTime", false, "CREATE_TIME");
        public final static Property UpdateTime = new Property(18, Long.class, "updateTime", false, "UPDATE_TIME");
        public final static Property QrCode = new Property(19, String.class, "qrCode", false, "QR_CODE");
        public final static Property Caption = new Property(20, String.class, "caption", false, "CAPTION");
    };

    private DaoSession daoSession;


    public ActInfoDao(DaoConfig config) {
        super(config);
    }
    
    public ActInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ACT_INFO' (" + //
                "'ACTIVITY_ID' TEXT PRIMARY KEY NOT NULL ," + // 0: activityId
                "'TITLE' TEXT," + // 1: title
                "'REMARK' TEXT," + // 2: remark
                "'START_TIME' INTEGER," + // 3: startTime
                "'END_TIME' INTEGER," + // 4: endTime
                "'RULES' TEXT," + // 5: rules
                "'PRIZE' TEXT," + // 6: prize
                "'PHOTO' TEXT," + // 7: photo
                "'ERECT_PHOTO' TEXT," + // 8: erectPhoto
                "'SQUARE_PHOTO' TEXT," + // 9: squarePhoto
                "'VIDEO' TEXT," + // 10: video
                "'THUMBNAIL' TEXT," + // 11: thumbnail
                "'URL' TEXT," + // 12: url
                "'RECOMMEND' INTEGER," + // 13: recommend
                "'GAME_ID' TEXT," + // 14: gameId
                "'PACKGE_NAME' TEXT," + // 15: packgeName
                "'NUMBER' INTEGER," + // 16: number
                "'CREATE_TIME' INTEGER," + // 17: createTime
                "'UPDATE_TIME' INTEGER," + // 18: updateTime
                "'QR_CODE' TEXT," + // 19: qrCode
                "'CAPTION' TEXT);"); // 20: caption
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ACT_INFO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ActInfo entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getActivityId());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(3, remark);
        }
 
        Long startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindLong(4, startTime);
        }
 
        Long endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindLong(5, endTime);
        }
 
        String rules = entity.getRules();
        if (rules != null) {
            stmt.bindString(6, rules);
        }
 
        String prize = entity.getPrize();
        if (prize != null) {
            stmt.bindString(7, prize);
        }
 
        String photo = entity.getPhoto();
        if (photo != null) {
            stmt.bindString(8, photo);
        }
 
        String erectPhoto = entity.getErectPhoto();
        if (erectPhoto != null) {
            stmt.bindString(9, erectPhoto);
        }
 
        String squarePhoto = entity.getSquarePhoto();
        if (squarePhoto != null) {
            stmt.bindString(10, squarePhoto);
        }
 
        String video = entity.getVideo();
        if (video != null) {
            stmt.bindString(11, video);
        }
 
        String thumbnail = entity.getThumbnail();
        if (thumbnail != null) {
            stmt.bindString(12, thumbnail);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(13, url);
        }
 
        Integer recommend = entity.getRecommend();
        if (recommend != null) {
            stmt.bindLong(14, recommend);
        }
 
        String gameId = entity.getGameId();
        if (gameId != null) {
            stmt.bindString(15, gameId);
        }
 
        String packgeName = entity.getPackgeName();
        if (packgeName != null) {
            stmt.bindString(16, packgeName);
        }
 
        Integer number = entity.getNumber();
        if (number != null) {
            stmt.bindLong(17, number);
        }
 
        Long createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindLong(18, createTime);
        }
 
        Long updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindLong(19, updateTime);
        }
 
        String qrCode = entity.getQrCode();
        if (qrCode != null) {
            stmt.bindString(20, qrCode);
        }
 
        String caption = entity.getCaption();
        if (caption != null) {
            stmt.bindString(21, caption);
        }
    }

    @Override
    protected void attachEntity(ActInfo entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ActInfo readEntity(Cursor cursor, int offset) {
        ActInfo entity = new ActInfo( //
            cursor.getString(offset + 0), // activityId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // remark
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // startTime
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // endTime
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // rules
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // prize
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // photo
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // erectPhoto
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // squarePhoto
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // video
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // thumbnail
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // url
            cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13), // recommend
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // gameId
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // packgeName
            cursor.isNull(offset + 16) ? null : cursor.getInt(offset + 16), // number
            cursor.isNull(offset + 17) ? null : cursor.getLong(offset + 17), // createTime
            cursor.isNull(offset + 18) ? null : cursor.getLong(offset + 18), // updateTime
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // qrCode
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20) // caption
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ActInfo entity, int offset) {
        entity.setActivityId(cursor.getString(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setRemark(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setStartTime(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setEndTime(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setRules(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setPrize(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPhoto(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setErectPhoto(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSquarePhoto(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setVideo(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setThumbnail(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setUrl(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setRecommend(cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13));
        entity.setGameId(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setPackgeName(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setNumber(cursor.isNull(offset + 16) ? null : cursor.getInt(offset + 16));
        entity.setCreateTime(cursor.isNull(offset + 17) ? null : cursor.getLong(offset + 17));
        entity.setUpdateTime(cursor.isNull(offset + 18) ? null : cursor.getLong(offset + 18));
        entity.setQrCode(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setCaption(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(ActInfo entity, long rowId) {
        return entity.getActivityId();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(ActInfo entity) {
        if(entity != null) {
            return entity.getActivityId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
