package com.atet.tvmarket.entity.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.atet.tvmarket.entity.dao.GameInfo;
import com.atet.tvmarket.entity.dao.ScreenShotInfo;
import com.atet.tvmarket.entity.dao.ThirdGameInfo;
import com.atet.tvmarket.entity.dao.ThirdGameDownInfo;
import com.atet.tvmarket.entity.dao.GameTypeInfo;
import com.atet.tvmarket.entity.dao.TypeToGame;
import com.atet.tvmarket.entity.dao.GameTopicInfo;
import com.atet.tvmarket.entity.dao.TopicToGame;
import com.atet.tvmarket.entity.dao.NewUploadToGame;
import com.atet.tvmarket.entity.dao.GameRanking;
import com.atet.tvmarket.entity.dao.GameSearchPinyinInfo;
import com.atet.tvmarket.entity.dao.AdInfo;
import com.atet.tvmarket.entity.dao.ActionUrl;
import com.atet.tvmarket.entity.dao.Extramap;
import com.atet.tvmarket.entity.dao.AdModelInfo;
import com.atet.tvmarket.entity.dao.ModelToAd;
import com.atet.tvmarket.entity.dao.ActInfo;
import com.atet.tvmarket.entity.dao.ActDetailPhoto;
import com.atet.tvmarket.entity.dao.GoodsInfo;
import com.atet.tvmarket.entity.dao.GoodsDetailPhoto;
import com.atet.tvmarket.entity.dao.GameGiftInfo;
import com.atet.tvmarket.entity.dao.GiftInfo;
import com.atet.tvmarket.entity.dao.UserGameGiftInfo;
import com.atet.tvmarket.entity.dao.UserGiftInfo;
import com.atet.tvmarket.entity.dao.UserGameToGift;
import com.atet.tvmarket.entity.dao.NoticeInfo;
import com.atet.tvmarket.entity.dao.VideoInfo;
import com.atet.tvmarket.entity.dao.GameScoreRecordInfo;
import com.atet.tvmarket.entity.dao.UserTaskRecord;
import com.atet.tvmarket.entity.dao.UpdateInterfaceInfo;
import com.atet.tvmarket.entity.dao.LocalUpdateInfo;

import com.atet.tvmarket.entity.dao.GameInfoDao;
import com.atet.tvmarket.entity.dao.ScreenShotInfoDao;
import com.atet.tvmarket.entity.dao.ThirdGameInfoDao;
import com.atet.tvmarket.entity.dao.ThirdGameDownInfoDao;
import com.atet.tvmarket.entity.dao.GameTypeInfoDao;
import com.atet.tvmarket.entity.dao.TypeToGameDao;
import com.atet.tvmarket.entity.dao.GameTopicInfoDao;
import com.atet.tvmarket.entity.dao.TopicToGameDao;
import com.atet.tvmarket.entity.dao.NewUploadToGameDao;
import com.atet.tvmarket.entity.dao.GameRankingDao;
import com.atet.tvmarket.entity.dao.GameSearchPinyinInfoDao;
import com.atet.tvmarket.entity.dao.AdInfoDao;
import com.atet.tvmarket.entity.dao.ActionUrlDao;
import com.atet.tvmarket.entity.dao.ExtramapDao;
import com.atet.tvmarket.entity.dao.AdModelInfoDao;
import com.atet.tvmarket.entity.dao.ModelToAdDao;
import com.atet.tvmarket.entity.dao.ActInfoDao;
import com.atet.tvmarket.entity.dao.ActDetailPhotoDao;
import com.atet.tvmarket.entity.dao.GoodsInfoDao;
import com.atet.tvmarket.entity.dao.GoodsDetailPhotoDao;
import com.atet.tvmarket.entity.dao.GameGiftInfoDao;
import com.atet.tvmarket.entity.dao.GiftInfoDao;
import com.atet.tvmarket.entity.dao.UserGameGiftInfoDao;
import com.atet.tvmarket.entity.dao.UserGiftInfoDao;
import com.atet.tvmarket.entity.dao.UserGameToGiftDao;
import com.atet.tvmarket.entity.dao.NoticeInfoDao;
import com.atet.tvmarket.entity.dao.VideoInfoDao;
import com.atet.tvmarket.entity.dao.GameScoreRecordInfoDao;
import com.atet.tvmarket.entity.dao.UserTaskRecordDao;
import com.atet.tvmarket.entity.dao.UpdateInterfaceInfoDao;
import com.atet.tvmarket.entity.dao.LocalUpdateInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gameInfoDaoConfig;
    private final DaoConfig screenShotInfoDaoConfig;
    private final DaoConfig thirdGameInfoDaoConfig;
    private final DaoConfig thirdGameDownInfoDaoConfig;
    private final DaoConfig gameTypeInfoDaoConfig;
    private final DaoConfig typeToGameDaoConfig;
    private final DaoConfig gameTopicInfoDaoConfig;
    private final DaoConfig topicToGameDaoConfig;
    private final DaoConfig newUploadToGameDaoConfig;
    private final DaoConfig gameRankingDaoConfig;
    private final DaoConfig gameSearchPinyinInfoDaoConfig;
    private final DaoConfig adInfoDaoConfig;
    private final DaoConfig actionUrlDaoConfig;
    private final DaoConfig extramapDaoConfig;
    private final DaoConfig adModelInfoDaoConfig;
    private final DaoConfig modelToAdDaoConfig;
    private final DaoConfig actInfoDaoConfig;
    private final DaoConfig actDetailPhotoDaoConfig;
    private final DaoConfig goodsInfoDaoConfig;
    private final DaoConfig goodsDetailPhotoDaoConfig;
    private final DaoConfig gameGiftInfoDaoConfig;
    private final DaoConfig giftInfoDaoConfig;
    private final DaoConfig userGameGiftInfoDaoConfig;
    private final DaoConfig userGiftInfoDaoConfig;
    private final DaoConfig userGameToGiftDaoConfig;
    private final DaoConfig noticeInfoDaoConfig;
    private final DaoConfig videoInfoDaoConfig;
    private final DaoConfig gameScoreRecordInfoDaoConfig;
    private final DaoConfig userTaskRecordDaoConfig;
    private final DaoConfig updateInterfaceInfoDaoConfig;
    private final DaoConfig localUpdateInfoDaoConfig;

    private final GameInfoDao gameInfoDao;
    private final ScreenShotInfoDao screenShotInfoDao;
    private final ThirdGameInfoDao thirdGameInfoDao;
    private final ThirdGameDownInfoDao thirdGameDownInfoDao;
    private final GameTypeInfoDao gameTypeInfoDao;
    private final TypeToGameDao typeToGameDao;
    private final GameTopicInfoDao gameTopicInfoDao;
    private final TopicToGameDao topicToGameDao;
    private final NewUploadToGameDao newUploadToGameDao;
    private final GameRankingDao gameRankingDao;
    private final GameSearchPinyinInfoDao gameSearchPinyinInfoDao;
    private final AdInfoDao adInfoDao;
    private final ActionUrlDao actionUrlDao;
    private final ExtramapDao extramapDao;
    private final AdModelInfoDao adModelInfoDao;
    private final ModelToAdDao modelToAdDao;
    private final ActInfoDao actInfoDao;
    private final ActDetailPhotoDao actDetailPhotoDao;
    private final GoodsInfoDao goodsInfoDao;
    private final GoodsDetailPhotoDao goodsDetailPhotoDao;
    private final GameGiftInfoDao gameGiftInfoDao;
    private final GiftInfoDao giftInfoDao;
    private final UserGameGiftInfoDao userGameGiftInfoDao;
    private final UserGiftInfoDao userGiftInfoDao;
    private final UserGameToGiftDao userGameToGiftDao;
    private final NoticeInfoDao noticeInfoDao;
    private final VideoInfoDao videoInfoDao;
    private final GameScoreRecordInfoDao gameScoreRecordInfoDao;
    private final UserTaskRecordDao userTaskRecordDao;
    private final UpdateInterfaceInfoDao updateInterfaceInfoDao;
    private final LocalUpdateInfoDao localUpdateInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gameInfoDaoConfig = daoConfigMap.get(GameInfoDao.class).clone();
        gameInfoDaoConfig.initIdentityScope(type);

        screenShotInfoDaoConfig = daoConfigMap.get(ScreenShotInfoDao.class).clone();
        screenShotInfoDaoConfig.initIdentityScope(type);

        thirdGameInfoDaoConfig = daoConfigMap.get(ThirdGameInfoDao.class).clone();
        thirdGameInfoDaoConfig.initIdentityScope(type);

        thirdGameDownInfoDaoConfig = daoConfigMap.get(ThirdGameDownInfoDao.class).clone();
        thirdGameDownInfoDaoConfig.initIdentityScope(type);

        gameTypeInfoDaoConfig = daoConfigMap.get(GameTypeInfoDao.class).clone();
        gameTypeInfoDaoConfig.initIdentityScope(type);

        typeToGameDaoConfig = daoConfigMap.get(TypeToGameDao.class).clone();
        typeToGameDaoConfig.initIdentityScope(type);

        gameTopicInfoDaoConfig = daoConfigMap.get(GameTopicInfoDao.class).clone();
        gameTopicInfoDaoConfig.initIdentityScope(type);

        topicToGameDaoConfig = daoConfigMap.get(TopicToGameDao.class).clone();
        topicToGameDaoConfig.initIdentityScope(type);

        newUploadToGameDaoConfig = daoConfigMap.get(NewUploadToGameDao.class).clone();
        newUploadToGameDaoConfig.initIdentityScope(type);

        gameRankingDaoConfig = daoConfigMap.get(GameRankingDao.class).clone();
        gameRankingDaoConfig.initIdentityScope(type);

        gameSearchPinyinInfoDaoConfig = daoConfigMap.get(GameSearchPinyinInfoDao.class).clone();
        gameSearchPinyinInfoDaoConfig.initIdentityScope(type);

        adInfoDaoConfig = daoConfigMap.get(AdInfoDao.class).clone();
        adInfoDaoConfig.initIdentityScope(type);

        actionUrlDaoConfig = daoConfigMap.get(ActionUrlDao.class).clone();
        actionUrlDaoConfig.initIdentityScope(type);

        extramapDaoConfig = daoConfigMap.get(ExtramapDao.class).clone();
        extramapDaoConfig.initIdentityScope(type);

        adModelInfoDaoConfig = daoConfigMap.get(AdModelInfoDao.class).clone();
        adModelInfoDaoConfig.initIdentityScope(type);

        modelToAdDaoConfig = daoConfigMap.get(ModelToAdDao.class).clone();
        modelToAdDaoConfig.initIdentityScope(type);

        actInfoDaoConfig = daoConfigMap.get(ActInfoDao.class).clone();
        actInfoDaoConfig.initIdentityScope(type);

        actDetailPhotoDaoConfig = daoConfigMap.get(ActDetailPhotoDao.class).clone();
        actDetailPhotoDaoConfig.initIdentityScope(type);

        goodsInfoDaoConfig = daoConfigMap.get(GoodsInfoDao.class).clone();
        goodsInfoDaoConfig.initIdentityScope(type);

        goodsDetailPhotoDaoConfig = daoConfigMap.get(GoodsDetailPhotoDao.class).clone();
        goodsDetailPhotoDaoConfig.initIdentityScope(type);

        gameGiftInfoDaoConfig = daoConfigMap.get(GameGiftInfoDao.class).clone();
        gameGiftInfoDaoConfig.initIdentityScope(type);

        giftInfoDaoConfig = daoConfigMap.get(GiftInfoDao.class).clone();
        giftInfoDaoConfig.initIdentityScope(type);

        userGameGiftInfoDaoConfig = daoConfigMap.get(UserGameGiftInfoDao.class).clone();
        userGameGiftInfoDaoConfig.initIdentityScope(type);

        userGiftInfoDaoConfig = daoConfigMap.get(UserGiftInfoDao.class).clone();
        userGiftInfoDaoConfig.initIdentityScope(type);

        userGameToGiftDaoConfig = daoConfigMap.get(UserGameToGiftDao.class).clone();
        userGameToGiftDaoConfig.initIdentityScope(type);

        noticeInfoDaoConfig = daoConfigMap.get(NoticeInfoDao.class).clone();
        noticeInfoDaoConfig.initIdentityScope(type);

        videoInfoDaoConfig = daoConfigMap.get(VideoInfoDao.class).clone();
        videoInfoDaoConfig.initIdentityScope(type);

        gameScoreRecordInfoDaoConfig = daoConfigMap.get(GameScoreRecordInfoDao.class).clone();
        gameScoreRecordInfoDaoConfig.initIdentityScope(type);

        userTaskRecordDaoConfig = daoConfigMap.get(UserTaskRecordDao.class).clone();
        userTaskRecordDaoConfig.initIdentityScope(type);

        updateInterfaceInfoDaoConfig = daoConfigMap.get(UpdateInterfaceInfoDao.class).clone();
        updateInterfaceInfoDaoConfig.initIdentityScope(type);

        localUpdateInfoDaoConfig = daoConfigMap.get(LocalUpdateInfoDao.class).clone();
        localUpdateInfoDaoConfig.initIdentityScope(type);

        gameInfoDao = new GameInfoDao(gameInfoDaoConfig, this);
        screenShotInfoDao = new ScreenShotInfoDao(screenShotInfoDaoConfig, this);
        thirdGameInfoDao = new ThirdGameInfoDao(thirdGameInfoDaoConfig, this);
        thirdGameDownInfoDao = new ThirdGameDownInfoDao(thirdGameDownInfoDaoConfig, this);
        gameTypeInfoDao = new GameTypeInfoDao(gameTypeInfoDaoConfig, this);
        typeToGameDao = new TypeToGameDao(typeToGameDaoConfig, this);
        gameTopicInfoDao = new GameTopicInfoDao(gameTopicInfoDaoConfig, this);
        topicToGameDao = new TopicToGameDao(topicToGameDaoConfig, this);
        newUploadToGameDao = new NewUploadToGameDao(newUploadToGameDaoConfig, this);
        gameRankingDao = new GameRankingDao(gameRankingDaoConfig, this);
        gameSearchPinyinInfoDao = new GameSearchPinyinInfoDao(gameSearchPinyinInfoDaoConfig, this);
        adInfoDao = new AdInfoDao(adInfoDaoConfig, this);
        actionUrlDao = new ActionUrlDao(actionUrlDaoConfig, this);
        extramapDao = new ExtramapDao(extramapDaoConfig, this);
        adModelInfoDao = new AdModelInfoDao(adModelInfoDaoConfig, this);
        modelToAdDao = new ModelToAdDao(modelToAdDaoConfig, this);
        actInfoDao = new ActInfoDao(actInfoDaoConfig, this);
        actDetailPhotoDao = new ActDetailPhotoDao(actDetailPhotoDaoConfig, this);
        goodsInfoDao = new GoodsInfoDao(goodsInfoDaoConfig, this);
        goodsDetailPhotoDao = new GoodsDetailPhotoDao(goodsDetailPhotoDaoConfig, this);
        gameGiftInfoDao = new GameGiftInfoDao(gameGiftInfoDaoConfig, this);
        giftInfoDao = new GiftInfoDao(giftInfoDaoConfig, this);
        userGameGiftInfoDao = new UserGameGiftInfoDao(userGameGiftInfoDaoConfig, this);
        userGiftInfoDao = new UserGiftInfoDao(userGiftInfoDaoConfig, this);
        userGameToGiftDao = new UserGameToGiftDao(userGameToGiftDaoConfig, this);
        noticeInfoDao = new NoticeInfoDao(noticeInfoDaoConfig, this);
        videoInfoDao = new VideoInfoDao(videoInfoDaoConfig, this);
        gameScoreRecordInfoDao = new GameScoreRecordInfoDao(gameScoreRecordInfoDaoConfig, this);
        userTaskRecordDao = new UserTaskRecordDao(userTaskRecordDaoConfig, this);
        updateInterfaceInfoDao = new UpdateInterfaceInfoDao(updateInterfaceInfoDaoConfig, this);
        localUpdateInfoDao = new LocalUpdateInfoDao(localUpdateInfoDaoConfig, this);

        registerDao(GameInfo.class, gameInfoDao);
        registerDao(ScreenShotInfo.class, screenShotInfoDao);
        registerDao(ThirdGameInfo.class, thirdGameInfoDao);
        registerDao(ThirdGameDownInfo.class, thirdGameDownInfoDao);
        registerDao(GameTypeInfo.class, gameTypeInfoDao);
        registerDao(TypeToGame.class, typeToGameDao);
        registerDao(GameTopicInfo.class, gameTopicInfoDao);
        registerDao(TopicToGame.class, topicToGameDao);
        registerDao(NewUploadToGame.class, newUploadToGameDao);
        registerDao(GameRanking.class, gameRankingDao);
        registerDao(GameSearchPinyinInfo.class, gameSearchPinyinInfoDao);
        registerDao(AdInfo.class, adInfoDao);
        registerDao(ActionUrl.class, actionUrlDao);
        registerDao(Extramap.class, extramapDao);
        registerDao(AdModelInfo.class, adModelInfoDao);
        registerDao(ModelToAd.class, modelToAdDao);
        registerDao(ActInfo.class, actInfoDao);
        registerDao(ActDetailPhoto.class, actDetailPhotoDao);
        registerDao(GoodsInfo.class, goodsInfoDao);
        registerDao(GoodsDetailPhoto.class, goodsDetailPhotoDao);
        registerDao(GameGiftInfo.class, gameGiftInfoDao);
        registerDao(GiftInfo.class, giftInfoDao);
        registerDao(UserGameGiftInfo.class, userGameGiftInfoDao);
        registerDao(UserGiftInfo.class, userGiftInfoDao);
        registerDao(UserGameToGift.class, userGameToGiftDao);
        registerDao(NoticeInfo.class, noticeInfoDao);
        registerDao(VideoInfo.class, videoInfoDao);
        registerDao(GameScoreRecordInfo.class, gameScoreRecordInfoDao);
        registerDao(UserTaskRecord.class, userTaskRecordDao);
        registerDao(UpdateInterfaceInfo.class, updateInterfaceInfoDao);
        registerDao(LocalUpdateInfo.class, localUpdateInfoDao);
    }
    
    public void clear() {
        gameInfoDaoConfig.getIdentityScope().clear();
        screenShotInfoDaoConfig.getIdentityScope().clear();
        thirdGameInfoDaoConfig.getIdentityScope().clear();
        thirdGameDownInfoDaoConfig.getIdentityScope().clear();
        gameTypeInfoDaoConfig.getIdentityScope().clear();
        typeToGameDaoConfig.getIdentityScope().clear();
        gameTopicInfoDaoConfig.getIdentityScope().clear();
        topicToGameDaoConfig.getIdentityScope().clear();
        newUploadToGameDaoConfig.getIdentityScope().clear();
        gameRankingDaoConfig.getIdentityScope().clear();
        gameSearchPinyinInfoDaoConfig.getIdentityScope().clear();
        adInfoDaoConfig.getIdentityScope().clear();
        actionUrlDaoConfig.getIdentityScope().clear();
        extramapDaoConfig.getIdentityScope().clear();
        adModelInfoDaoConfig.getIdentityScope().clear();
        modelToAdDaoConfig.getIdentityScope().clear();
        actInfoDaoConfig.getIdentityScope().clear();
        actDetailPhotoDaoConfig.getIdentityScope().clear();
        goodsInfoDaoConfig.getIdentityScope().clear();
        goodsDetailPhotoDaoConfig.getIdentityScope().clear();
        gameGiftInfoDaoConfig.getIdentityScope().clear();
        giftInfoDaoConfig.getIdentityScope().clear();
        userGameGiftInfoDaoConfig.getIdentityScope().clear();
        userGiftInfoDaoConfig.getIdentityScope().clear();
        userGameToGiftDaoConfig.getIdentityScope().clear();
        noticeInfoDaoConfig.getIdentityScope().clear();
        videoInfoDaoConfig.getIdentityScope().clear();
        gameScoreRecordInfoDaoConfig.getIdentityScope().clear();
        userTaskRecordDaoConfig.getIdentityScope().clear();
        updateInterfaceInfoDaoConfig.getIdentityScope().clear();
        localUpdateInfoDaoConfig.getIdentityScope().clear();
    }

    public GameInfoDao getGameInfoDao() {
        return gameInfoDao;
    }

    public ScreenShotInfoDao getScreenShotInfoDao() {
        return screenShotInfoDao;
    }

    public ThirdGameInfoDao getThirdGameInfoDao() {
        return thirdGameInfoDao;
    }

    public ThirdGameDownInfoDao getThirdGameDownInfoDao() {
        return thirdGameDownInfoDao;
    }

    public GameTypeInfoDao getGameTypeInfoDao() {
        return gameTypeInfoDao;
    }

    public TypeToGameDao getTypeToGameDao() {
        return typeToGameDao;
    }

    public GameTopicInfoDao getGameTopicInfoDao() {
        return gameTopicInfoDao;
    }

    public TopicToGameDao getTopicToGameDao() {
        return topicToGameDao;
    }

    public NewUploadToGameDao getNewUploadToGameDao() {
        return newUploadToGameDao;
    }

    public GameRankingDao getGameRankingDao() {
        return gameRankingDao;
    }

    public GameSearchPinyinInfoDao getGameSearchPinyinInfoDao() {
        return gameSearchPinyinInfoDao;
    }

    public AdInfoDao getAdInfoDao() {
        return adInfoDao;
    }

    public ActionUrlDao getActionUrlDao() {
        return actionUrlDao;
    }

    public ExtramapDao getExtramapDao() {
        return extramapDao;
    }

    public AdModelInfoDao getAdModelInfoDao() {
        return adModelInfoDao;
    }

    public ModelToAdDao getModelToAdDao() {
        return modelToAdDao;
    }

    public ActInfoDao getActInfoDao() {
        return actInfoDao;
    }

    public ActDetailPhotoDao getActDetailPhotoDao() {
        return actDetailPhotoDao;
    }

    public GoodsInfoDao getGoodsInfoDao() {
        return goodsInfoDao;
    }

    public GoodsDetailPhotoDao getGoodsDetailPhotoDao() {
        return goodsDetailPhotoDao;
    }

    public GameGiftInfoDao getGameGiftInfoDao() {
        return gameGiftInfoDao;
    }

    public GiftInfoDao getGiftInfoDao() {
        return giftInfoDao;
    }

    public UserGameGiftInfoDao getUserGameGiftInfoDao() {
        return userGameGiftInfoDao;
    }

    public UserGiftInfoDao getUserGiftInfoDao() {
        return userGiftInfoDao;
    }

    public UserGameToGiftDao getUserGameToGiftDao() {
        return userGameToGiftDao;
    }

    public NoticeInfoDao getNoticeInfoDao() {
        return noticeInfoDao;
    }

    public VideoInfoDao getVideoInfoDao() {
        return videoInfoDao;
    }

    public GameScoreRecordInfoDao getGameScoreRecordInfoDao() {
        return gameScoreRecordInfoDao;
    }

    public UserTaskRecordDao getUserTaskRecordDao() {
        return userTaskRecordDao;
    }

    public UpdateInterfaceInfoDao getUpdateInterfaceInfoDao() {
        return updateInterfaceInfoDao;
    }

    public LocalUpdateInfoDao getLocalUpdateInfoDao() {
        return localUpdateInfoDao;
    }

}
