package com.atet.tvmarket.entity.dao;

import java.util.List;
import com.atet.tvmarket.entity.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table GAME_GIFT_INFO.
 */
public class GameGiftInfo implements java.io.Serializable {

    /** Not-null value. */
    private String gameid;
    private String gameName;
    private String maxPhoto;
    private String minPhoto;
    private Integer sortNum;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient GameGiftInfoDao myDao;

    private List<GiftInfo> giftData;

    // KEEP FIELDS - put your custom fields here
    private static final long serialVersionUID = 1L;
    // KEEP FIELDS END

    public GameGiftInfo() {
    }

    public GameGiftInfo(String gameid) {
        this.gameid = gameid;
    }

    public GameGiftInfo(String gameid, String gameName, String maxPhoto, String minPhoto, Integer sortNum) {
        this.gameid = gameid;
        this.gameName = gameName;
        this.maxPhoto = maxPhoto;
        this.minPhoto = minPhoto;
        this.sortNum = sortNum;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getGameGiftInfoDao() : null;
    }

    /** Not-null value. */
    public String getGameid() {
        return gameid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGameid(String gameid) {
        this.gameid = gameid;
    }

    public String getGameName() {
        return gameName;
    }

    public void setGameName(String gameName) {
        this.gameName = gameName;
    }

    public String getMaxPhoto() {
        return maxPhoto;
    }

    public void setMaxPhoto(String maxPhoto) {
        this.maxPhoto = maxPhoto;
    }

    public String getMinPhoto() {
        return minPhoto;
    }

    public void setMinPhoto(String minPhoto) {
        this.minPhoto = minPhoto;
    }

    public Integer getSortNum() {
        return sortNum;
    }

    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<GiftInfo> getGiftData() {
        if (giftData == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            GiftInfoDao targetDao = daoSession.getGiftInfoDao();
            List<GiftInfo> giftDataNew = targetDao._queryGameGiftInfo_GiftData(gameid);
            synchronized (this) {
                if(giftData == null) {
                    giftData = giftDataNew;
                }
            }
        }
        return giftData;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetGiftData() {
        giftData = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
	@Override
	public String toString() {
		return "GameGiftInfo [gameId=" + gameid + ", gameName=" + gameName
				+ ", maxPhoto=" + maxPhoto + ", minPhoto=" + minPhoto
				+ ", sortNum=" + sortNum + ", giftData=" + giftData + "]";
	}
    // KEEP METHODS END

}
