package com.atet.tvmarket.entity.dao;

import java.util.List;
import com.atet.tvmarket.entity.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table GAME_INFO.
 */
public class GameInfo implements java.io.Serializable, com.atet.tvmarket.entity.AutoType {

    /** Not-null value. */
    private String gameId;
    private String gameName;
    private String cpId;
    private String file;
    private String maxPhoto;
    private String middlePhoto;
    private String minPhoto;
    private String erectPhoto;
    private Integer fitAge;
    private Double startLevel;
    private Integer gameDownCount;
    private Integer gameSize;
    private Integer gamePrice;
    private String remark;
    private String appendixZip;
    private Long createTime;
    private Long updateTime;
    private String packageName;
    private String versionName;
    private Integer versionCode;
    private Integer handleType;
    private Integer isGood;
    private Double shortNo;
    private String typeId;
    private String typeName;
    private String midDownAdress;
    private Integer downToken;
    private Integer gameType;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient GameInfoDao myDao;

    private List<ScreenShotInfo> imgs;

    // KEEP FIELDS - put your custom fields here
	private static final long serialVersionUID = 1L;
    // KEEP FIELDS END

    public GameInfo() {
    }

    public GameInfo(String gameId) {
        this.gameId = gameId;
    }

    public GameInfo(String gameId, String gameName, String cpId, String file, String maxPhoto, String middlePhoto, String minPhoto, String erectPhoto, Integer fitAge, Double startLevel, Integer gameDownCount, Integer gameSize, Integer gamePrice, String remark, String appendixZip, Long createTime, Long updateTime, String packageName, String versionName, Integer versionCode, Integer handleType, Integer isGood, Double shortNo, String typeId, String typeName, String midDownAdress, Integer downToken, Integer gameType) {
        this.gameId = gameId;
        this.gameName = gameName;
        this.cpId = cpId;
        this.file = file;
        this.maxPhoto = maxPhoto;
        this.middlePhoto = middlePhoto;
        this.minPhoto = minPhoto;
        this.erectPhoto = erectPhoto;
        this.fitAge = fitAge;
        this.startLevel = startLevel;
        this.gameDownCount = gameDownCount;
        this.gameSize = gameSize;
        this.gamePrice = gamePrice;
        this.remark = remark;
        this.appendixZip = appendixZip;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.packageName = packageName;
        this.versionName = versionName;
        this.versionCode = versionCode;
        this.handleType = handleType;
        this.isGood = isGood;
        this.shortNo = shortNo;
        this.typeId = typeId;
        this.typeName = typeName;
        this.midDownAdress = midDownAdress;
        this.downToken = downToken;
        this.gameType = gameType;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getGameInfoDao() : null;
    }

    /** Not-null value. */
    public String getGameId() {
        return gameId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGameId(String gameId) {
        this.gameId = gameId;
    }

    public String getGameName() {
        return gameName;
    }

    public void setGameName(String gameName) {
        this.gameName = gameName;
    }

    public String getCpId() {
        return cpId;
    }

    public void setCpId(String cpId) {
        this.cpId = cpId;
    }

    public String getFile() {
        return file;
    }

    public void setFile(String file) {
        this.file = file;
    }

    public String getMaxPhoto() {
        return maxPhoto;
    }

    public void setMaxPhoto(String maxPhoto) {
        this.maxPhoto = maxPhoto;
    }

    public String getMiddlePhoto() {
        return middlePhoto;
    }

    public void setMiddlePhoto(String middlePhoto) {
        this.middlePhoto = middlePhoto;
    }

    public String getMinPhoto() {
        return minPhoto;
    }

    public void setMinPhoto(String minPhoto) {
        this.minPhoto = minPhoto;
    }

    public String getErectPhoto() {
        return erectPhoto;
    }

    public void setErectPhoto(String erectPhoto) {
        this.erectPhoto = erectPhoto;
    }

    public Integer getFitAge() {
        return fitAge;
    }

    public void setFitAge(Integer fitAge) {
        this.fitAge = fitAge;
    }

    public Double getStartLevel() {
        return startLevel;
    }

    public void setStartLevel(Double startLevel) {
        this.startLevel = startLevel;
    }

    public Integer getGameDownCount() {
        return gameDownCount;
    }

    public void setGameDownCount(Integer gameDownCount) {
        this.gameDownCount = gameDownCount;
    }

    public Integer getGameSize() {
        return gameSize;
    }

    public void setGameSize(Integer gameSize) {
        this.gameSize = gameSize;
    }

    public Integer getGamePrice() {
        return gamePrice;
    }

    public void setGamePrice(Integer gamePrice) {
        this.gamePrice = gamePrice;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getAppendixZip() {
        return appendixZip;
    }

    public void setAppendixZip(String appendixZip) {
        this.appendixZip = appendixZip;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public String getVersionName() {
        return versionName;
    }

    public void setVersionName(String versionName) {
        this.versionName = versionName;
    }

    public Integer getVersionCode() {
        return versionCode;
    }

    public void setVersionCode(Integer versionCode) {
        this.versionCode = versionCode;
    }

    public Integer getHandleType() {
        return handleType;
    }

    public void setHandleType(Integer handleType) {
        this.handleType = handleType;
    }

    public Integer getIsGood() {
        return isGood;
    }

    public void setIsGood(Integer isGood) {
        this.isGood = isGood;
    }

    public Double getShortNo() {
        return shortNo;
    }

    public void setShortNo(Double shortNo) {
        this.shortNo = shortNo;
    }

    public String getTypeId() {
        return typeId;
    }

    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public String getMidDownAdress() {
        return midDownAdress;
    }

    public void setMidDownAdress(String midDownAdress) {
        this.midDownAdress = midDownAdress;
    }

    public Integer getDownToken() {
        return downToken;
    }

    public void setDownToken(Integer downToken) {
        this.downToken = downToken;
    }

    public Integer getGameType() {
        return gameType;
    }

    public void setGameType(Integer gameType) {
        this.gameType = gameType;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<ScreenShotInfo> getImgs() {
        if (imgs == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ScreenShotInfoDao targetDao = daoSession.getScreenShotInfoDao();
            List<ScreenShotInfo> imgsNew = targetDao._queryGameInfo_Imgs(gameId);
            synchronized (this) {
                if(imgs == null) {
                    imgs = imgsNew;
                }
            }
        }
        return imgs;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetImgs() {
        imgs = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
	@Override
	public String toString() {
		return "GameInfo [gameId=" + gameId + ", gameName="
				+ gameName + ", cpId=" + cpId + ", file=" + file
				+ ", maxPhoto=" + maxPhoto + ", middlePhoto=" + middlePhoto
				+ ", minPhoto=" + minPhoto + ", erectPhoto=" + erectPhoto
				+ ", fitAge=" + fitAge + ", startLevel=" + startLevel
				+ ", gameDownCount=" + gameDownCount + ", gameSize=" + gameSize
				+ ", gamePrice=" + gamePrice + ", remark=" + remark
				+ ", appendixZip=" + appendixZip + ", createTime=" + createTime
				+ ", updateTime=" + updateTime + ", packageName=" + packageName
				+ ", versionName=" + versionName + ", versionCode="
				+ versionCode + ", handleType=" + handleType + ", isGood="
				+ isGood + ", shortNo=" + shortNo + ", typeId=" + typeId
				+ ", typeName=" + typeName + ", midDownAdress=" + midDownAdress
				+ ", downToken=" + downToken + ", gameType=" + gameType
				+ ", imgs=" + imgs + "]";
	}
    // KEEP METHODS END

}
