package com.atet.tvmarket.entity.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table GAME_SEARCH_PINYIN_INFO.
 */
public class GameSearchPinyinInfo implements java.io.Serializable {

    private Long id;
    private String gameId;
    private String gameName;
    private String pinyin;
    private Integer downCount;
    private Double starLevel;
    private String icon;
    private Integer gameSize;
    private String file;
    private String appendixZip;
    private Integer type;

    // KEEP FIELDS - put your custom fields here
	private static final long serialVersionUID = 1L;
    // KEEP FIELDS END

    public GameSearchPinyinInfo() {
    }

    public GameSearchPinyinInfo(Long id) {
        this.id = id;
    }

    public GameSearchPinyinInfo(Long id, String gameId, String gameName, String pinyin, Integer downCount, Double starLevel, String icon, Integer gameSize, String file, String appendixZip, Integer type) {
        this.id = id;
        this.gameId = gameId;
        this.gameName = gameName;
        this.pinyin = pinyin;
        this.downCount = downCount;
        this.starLevel = starLevel;
        this.icon = icon;
        this.gameSize = gameSize;
        this.file = file;
        this.appendixZip = appendixZip;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGameId() {
        return gameId;
    }

    public void setGameId(String gameId) {
        this.gameId = gameId;
    }

    public String getGameName() {
        return gameName;
    }

    public void setGameName(String gameName) {
        this.gameName = gameName;
    }

    public String getPinyin() {
        return pinyin;
    }

    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    public Integer getDownCount() {
        return downCount;
    }

    public void setDownCount(Integer downCount) {
        this.downCount = downCount;
    }

    public Double getStarLevel() {
        return starLevel;
    }

    public void setStarLevel(Double starLevel) {
        this.starLevel = starLevel;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public Integer getGameSize() {
        return gameSize;
    }

    public void setGameSize(Integer gameSize) {
        this.gameSize = gameSize;
    }

    public String getFile() {
        return file;
    }

    public void setFile(String file) {
        this.file = file;
    }

    public String getAppendixZip() {
        return appendixZip;
    }

    public void setAppendixZip(String appendixZip) {
        this.appendixZip = appendixZip;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    // KEEP METHODS - put your custom methods here
	@Override
	public String toString() {
		return "GameSearchPinyinInfo [id=" + id + ", gameId=" + gameId
				+ ", gameName=" + gameName + ", pinyin=" + pinyin
				+ ", downCount=" + downCount + ", starLevel=" + starLevel
				+ ", icon=" + icon + ", gameSize=" + gameSize + ", file="
				+ file + ", appendixZip=" + appendixZip + ",type=" + type + "]";
	}
    // KEEP METHODS END

}
