package com.atet.tvmarket.entity.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table GAME_SCORE_RECORD_INFO.
 */
public class GameScoreRecordInfo implements java.io.Serializable {

    private Long id;
    private String gameId;
    private String userId;
    private Integer score;

    // KEEP FIELDS - put your custom fields here
	private static final long serialVersionUID = 1L;
    // KEEP FIELDS END

    public GameScoreRecordInfo() {
    }

    public GameScoreRecordInfo(Long id) {
        this.id = id;
    }

    public GameScoreRecordInfo(Long id, String gameId, String userId, Integer score) {
        this.id = id;
        this.gameId = gameId;
        this.userId = userId;
        this.score = score;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGameId() {
        return gameId;
    }

    public void setGameId(String gameId) {
        this.gameId = gameId;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public Integer getScore() {
        return score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
