package com.atet.tvmarket.entity.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table GIFT_INFO.
 */
public class GiftInfo implements java.io.Serializable {

    /** Not-null value. */
    private String giftPackageid;
    private String name;
    private String useMethod;
    private String remark;
    private Long startTime;
    private Long endTime;
    private Integer number;
    /** Not-null value. */
    private String gameId;

    // KEEP FIELDS - put your custom fields here
	private static final long serialVersionUID = 1L;
    // KEEP FIELDS END

    public GiftInfo() {
    }

    public GiftInfo(String giftPackageid) {
        this.giftPackageid = giftPackageid;
    }

    public GiftInfo(String giftPackageid, String name, String useMethod, String remark, Long startTime, Long endTime, Integer number, String gameId) {
        this.giftPackageid = giftPackageid;
        this.name = name;
        this.useMethod = useMethod;
        this.remark = remark;
        this.startTime = startTime;
        this.endTime = endTime;
        this.number = number;
        this.gameId = gameId;
    }

    /** Not-null value. */
    public String getGiftPackageid() {
        return giftPackageid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGiftPackageid(String giftPackageid) {
        this.giftPackageid = giftPackageid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUseMethod() {
        return useMethod;
    }

    public void setUseMethod(String useMethod) {
        this.useMethod = useMethod;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    public Integer getNumber() {
        return number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    /** Not-null value. */
    public String getGameId() {
        return gameId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGameId(String gameId) {
        this.gameId = gameId;
    }

    // KEEP METHODS - put your custom methods here
	@Override
	public String toString() {
		return "GiftInfo [giftPackageid=" + giftPackageid + ", name=" + name
				+ ", useMethod=" + useMethod + ", remark=" + remark
				+ ", startTime=" + startTime + ", endTime=" + endTime
				+ ", number=" + number + ", gameId=" + gameId + "]";
	}
    // KEEP METHODS END

}
