package com.atet.tvmarket.entity.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table GOODS_DETAIL_PHOTO.
 */
public class GoodsDetailPhoto implements java.io.Serializable {

    private Long id;
    private String picture;
    /** Not-null value. */
    private String goodsId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GoodsDetailPhoto() {
    }

    public GoodsDetailPhoto(Long id) {
        this.id = id;
    }

    public GoodsDetailPhoto(Long id, String picture, String goodsId) {
        this.id = id;
        this.picture = picture;
        this.goodsId = goodsId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPicture() {
        return picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

    /** Not-null value. */
    public String getGoodsId() {
        return goodsId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
