package com.atet.tvmarket.entity.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table LOCAL_SUB_TYPE_ID.
 */
public class LocalSubTypeId {

    private String typeId;
    private Long localUpdateTime;
    private String localname;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LocalSubTypeId() {
    }

    public LocalSubTypeId(String typeId) {
        this.typeId = typeId;
    }

    public LocalSubTypeId(String typeId, Long localUpdateTime, String localname) {
        this.typeId = typeId;
        this.localUpdateTime = localUpdateTime;
        this.localname = localname;
    }

    public String getTypeId() {
        return typeId;
    }

    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    public Long getLocalUpdateTime() {
        return localUpdateTime;
    }

    public void setLocalUpdateTime(Long localUpdateTime) {
        this.localUpdateTime = localUpdateTime;
    }

    public String getLocalname() {
        return localname;
    }

    public void setLocalname(String localname) {
        this.localname = localname;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
