package com.atet.tvmarket.entity.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.atet.tvmarket.entity.dao.LocalUpdateInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table LOCAL_UPDATE_INFO.
*/
public class LocalUpdateInfoDao extends AbstractDao<LocalUpdateInfo, String> {

    public static final String TABLENAME = "LOCAL_UPDATE_INFO";

    /**
     * Properties of entity LocalUpdateInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property LocalUniqueId = new Property(0, String.class, "localUniqueId", true, "LOCAL_UNIQUE_ID");
        public final static Property LocalName = new Property(1, String.class, "localName", false, "LOCAL_NAME");
        public final static Property LocalSubId = new Property(2, String.class, "localSubId", false, "LOCAL_SUB_ID");
        public final static Property LocalUpdateTime = new Property(3, Long.class, "localUpdateTime", false, "LOCAL_UPDATE_TIME");
        public final static Property LocalState = new Property(4, Integer.class, "localState", false, "LOCAL_STATE");
    };

    private DaoSession daoSession;


    public LocalUpdateInfoDao(DaoConfig config) {
        super(config);
    }
    
    public LocalUpdateInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'LOCAL_UPDATE_INFO' (" + //
                "'LOCAL_UNIQUE_ID' TEXT PRIMARY KEY NOT NULL ," + // 0: localUniqueId
                "'LOCAL_NAME' TEXT," + // 1: localName
                "'LOCAL_SUB_ID' TEXT," + // 2: localSubId
                "'LOCAL_UPDATE_TIME' INTEGER," + // 3: localUpdateTime
                "'LOCAL_STATE' INTEGER);"); // 4: localState
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'LOCAL_UPDATE_INFO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, LocalUpdateInfo entity) {
        stmt.clearBindings();
 
        String localUniqueId = entity.getLocalUniqueId();
        if (localUniqueId != null) {
            stmt.bindString(1, localUniqueId);
        }
 
        String localName = entity.getLocalName();
        if (localName != null) {
            stmt.bindString(2, localName);
        }
 
        String localSubId = entity.getLocalSubId();
        if (localSubId != null) {
            stmt.bindString(3, localSubId);
        }
 
        Long localUpdateTime = entity.getLocalUpdateTime();
        if (localUpdateTime != null) {
            stmt.bindLong(4, localUpdateTime);
        }
 
        Integer localState = entity.getLocalState();
        if (localState != null) {
            stmt.bindLong(5, localState);
        }
    }

    @Override
    protected void attachEntity(LocalUpdateInfo entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public LocalUpdateInfo readEntity(Cursor cursor, int offset) {
        LocalUpdateInfo entity = new LocalUpdateInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // localUniqueId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // localName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // localSubId
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // localUpdateTime
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4) // localState
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, LocalUpdateInfo entity, int offset) {
        entity.setLocalUniqueId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setLocalName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLocalSubId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLocalUpdateTime(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setLocalState(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(LocalUpdateInfo entity, long rowId) {
        return entity.getLocalUniqueId();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(LocalUpdateInfo entity) {
        if(entity != null) {
            return entity.getLocalUniqueId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUpdateInterfaceInfoDao().getAllColumns());
            builder.append(" FROM LOCAL_UPDATE_INFO T");
            builder.append(" LEFT JOIN UPDATE_INTERFACE_INFO T0 ON T.'LOCAL_UNIQUE_ID'=T0.'UNIQUE_ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected LocalUpdateInfo loadCurrentDeep(Cursor cursor, boolean lock) {
        LocalUpdateInfo entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        UpdateInterfaceInfo updateInterfaceInfo = loadCurrentOther(daoSession.getUpdateInterfaceInfoDao(), cursor, offset);
        entity.setUpdateInterfaceInfo(updateInterfaceInfo);

        return entity;    
    }

    public LocalUpdateInfo loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<LocalUpdateInfo> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<LocalUpdateInfo> list = new ArrayList<LocalUpdateInfo>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<LocalUpdateInfo> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<LocalUpdateInfo> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
