package com.atet.tvmarket.entity.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.atet.tvmarket.entity.dao.ModelToAd;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MODEL_TO_AD.
*/
public class ModelToAdDao extends AbstractDao<ModelToAd, Long> {

    public static final String TABLENAME = "MODEL_TO_AD";

    /**
     * Properties of entity ModelToAd.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property AdId = new Property(1, String.class, "AdId", false, "AD_ID");
        public final static Property ModelKey = new Property(2, long.class, "modelKey", false, "MODEL_KEY");
        public final static Property ReturnOrder = new Property(3, Integer.class, "returnOrder", false, "RETURN_ORDER");
    };

    private DaoSession daoSession;

    private Query<ModelToAd> adModelInfo_ModelToAdListQuery;

    public ModelToAdDao(DaoConfig config) {
        super(config);
    }
    
    public ModelToAdDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MODEL_TO_AD' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'AD_ID' TEXT NOT NULL ," + // 1: AdId
                "'MODEL_KEY' INTEGER NOT NULL ," + // 2: modelKey
                "'RETURN_ORDER' INTEGER);"); // 3: returnOrder
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MODEL_TO_AD'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ModelToAd entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getAdId());
        stmt.bindLong(3, entity.getModelKey());
 
        Integer returnOrder = entity.getReturnOrder();
        if (returnOrder != null) {
            stmt.bindLong(4, returnOrder);
        }
    }

    @Override
    protected void attachEntity(ModelToAd entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ModelToAd readEntity(Cursor cursor, int offset) {
        ModelToAd entity = new ModelToAd( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // AdId
            cursor.getLong(offset + 2), // modelKey
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3) // returnOrder
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ModelToAd entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAdId(cursor.getString(offset + 1));
        entity.setModelKey(cursor.getLong(offset + 2));
        entity.setReturnOrder(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ModelToAd entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ModelToAd entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "modelToAdList" to-many relationship of AdModelInfo. */
    public List<ModelToAd> _queryAdModelInfo_ModelToAdList(long modelKey) {
        synchronized (this) {
            if (adModelInfo_ModelToAdListQuery == null) {
                QueryBuilder<ModelToAd> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ModelKey.eq(null));
                queryBuilder.orderRaw("RETURN_ORDER ASC");
                adModelInfo_ModelToAdListQuery = queryBuilder.build();
            }
        }
        Query<ModelToAd> query = adModelInfo_ModelToAdListQuery.forCurrentThread();
        query.setParameter(0, modelKey);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getAdInfoDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getAdModelInfoDao().getAllColumns());
            builder.append(" FROM MODEL_TO_AD T");
            builder.append(" LEFT JOIN AD_INFO T0 ON T.'AD_ID'=T0.'AD_ID'");
            builder.append(" LEFT JOIN AD_MODEL_INFO T1 ON T.'MODEL_KEY'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected ModelToAd loadCurrentDeep(Cursor cursor, boolean lock) {
        ModelToAd entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        AdInfo adInfo = loadCurrentOther(daoSession.getAdInfoDao(), cursor, offset);
         if(adInfo != null) {
            entity.setAdInfo(adInfo);
        }
        offset += daoSession.getAdInfoDao().getAllColumns().length;

        AdModelInfo adModelInfo = loadCurrentOther(daoSession.getAdModelInfoDao(), cursor, offset);
         if(adModelInfo != null) {
            entity.setAdModelInfo(adModelInfo);
        }

        return entity;    
    }

    public ModelToAd loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<ModelToAd> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ModelToAd> list = new ArrayList<ModelToAd>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<ModelToAd> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<ModelToAd> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
