package com.atet.tvmarket.entity.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.atet.tvmarket.entity.dao.ScreenShotInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SCREEN_SHOT_INFO.
*/
public class ScreenShotInfoDao extends AbstractDao<ScreenShotInfo, Long> {

    public static final String TABLENAME = "SCREEN_SHOT_INFO";

    /**
     * Properties of entity ScreenShotInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PhotoUrl = new Property(1, String.class, "photoUrl", false, "PHOTO_URL");
        public final static Property Type = new Property(2, Integer.class, "type", false, "TYPE");
        public final static Property Number = new Property(3, Integer.class, "number", false, "NUMBER");
        public final static Property GameId = new Property(4, String.class, "gameId", false, "GAME_ID");
    };

    private DaoSession daoSession;

    private Query<ScreenShotInfo> gameInfo_ImgsQuery;

    public ScreenShotInfoDao(DaoConfig config) {
        super(config);
    }
    
    public ScreenShotInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SCREEN_SHOT_INFO' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'PHOTO_URL' TEXT," + // 1: photoUrl
                "'TYPE' INTEGER," + // 2: type
                "'NUMBER' INTEGER," + // 3: number
                "'GAME_ID' TEXT NOT NULL );"); // 4: gameId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SCREEN_SHOT_INFO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ScreenShotInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String photoUrl = entity.getPhotoUrl();
        if (photoUrl != null) {
            stmt.bindString(2, photoUrl);
        }
 
        Integer type = entity.getType();
        if (type != null) {
            stmt.bindLong(3, type);
        }
 
        Integer number = entity.getNumber();
        if (number != null) {
            stmt.bindLong(4, number);
        }
        stmt.bindString(5, entity.getGameId());
    }

    @Override
    protected void attachEntity(ScreenShotInfo entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ScreenShotInfo readEntity(Cursor cursor, int offset) {
        ScreenShotInfo entity = new ScreenShotInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // photoUrl
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // type
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // number
            cursor.getString(offset + 4) // gameId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ScreenShotInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPhotoUrl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setType(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setNumber(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setGameId(cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ScreenShotInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ScreenShotInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "imgs" to-many relationship of GameInfo. */
    public List<ScreenShotInfo> _queryGameInfo_Imgs(String gameId) {
        synchronized (this) {
            if (gameInfo_ImgsQuery == null) {
                QueryBuilder<ScreenShotInfo> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.GameId.eq(null));
                gameInfo_ImgsQuery = queryBuilder.build();
            }
        }
        Query<ScreenShotInfo> query = gameInfo_ImgsQuery.forCurrentThread();
        query.setParameter(0, gameId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getGameInfoDao().getAllColumns());
            builder.append(" FROM SCREEN_SHOT_INFO T");
            builder.append(" LEFT JOIN GAME_INFO T0 ON T.'GAME_ID'=T0.'GAME_ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected ScreenShotInfo loadCurrentDeep(Cursor cursor, boolean lock) {
        ScreenShotInfo entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        GameInfo gameInfo = loadCurrentOther(daoSession.getGameInfoDao(), cursor, offset);
         if(gameInfo != null) {
            entity.setGameInfo(gameInfo);
        }

        return entity;    
    }

    public ScreenShotInfo loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<ScreenShotInfo> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ScreenShotInfo> list = new ArrayList<ScreenShotInfo>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<ScreenShotInfo> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<ScreenShotInfo> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
