package com.atet.tvmarket.entity.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table SUB_TYPE_ID.
 */
public class SubTypeId {

    private String typeId;
    private Long updateTime;
    private String interfaceName;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SubTypeId() {
    }

    public SubTypeId(String typeId) {
        this.typeId = typeId;
    }

    public SubTypeId(String typeId, Long updateTime, String interfaceName) {
        this.typeId = typeId;
        this.updateTime = updateTime;
        this.interfaceName = interfaceName;
    }

    public String getTypeId() {
        return typeId;
    }

    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    public Long getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    public String getInterfaceName() {
        return interfaceName;
    }

    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
