package com.atet.tvmarket.entity.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.atet.tvmarket.entity.dao.TopicToGame;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table TOPIC_TO_GAME.
*/
public class TopicToGameDao extends AbstractDao<TopicToGame, Long> {

    public static final String TABLENAME = "TOPIC_TO_GAME";

    /**
     * Properties of entity TopicToGame.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ReturnOrder = new Property(1, Integer.class, "returnOrder", false, "RETURN_ORDER");
        public final static Property Type = new Property(2, Integer.class, "type", false, "TYPE");
        public final static Property TopicId = new Property(3, String.class, "topicId", false, "TOPIC_ID");
        public final static Property GameId = new Property(4, String.class, "gameId", false, "GAME_ID");
    };

    private DaoSession daoSession;

    private Query<TopicToGame> gameTopicInfo_TopicToGameListQuery;

    public TopicToGameDao(DaoConfig config) {
        super(config);
    }
    
    public TopicToGameDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TOPIC_TO_GAME' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'RETURN_ORDER' INTEGER," + // 1: returnOrder
                "'TYPE' INTEGER," + // 2: type
                "'TOPIC_ID' TEXT NOT NULL ," + // 3: topicId
                "'GAME_ID' TEXT NOT NULL );"); // 4: gameId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TOPIC_TO_GAME'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TopicToGame entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer returnOrder = entity.getReturnOrder();
        if (returnOrder != null) {
            stmt.bindLong(2, returnOrder);
        }
 
        Integer type = entity.getType();
        if (type != null) {
            stmt.bindLong(3, type);
        }
        stmt.bindString(4, entity.getTopicId());
        stmt.bindString(5, entity.getGameId());
    }

    @Override
    protected void attachEntity(TopicToGame entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TopicToGame readEntity(Cursor cursor, int offset) {
        TopicToGame entity = new TopicToGame( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // returnOrder
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // type
            cursor.getString(offset + 3), // topicId
            cursor.getString(offset + 4) // gameId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TopicToGame entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setReturnOrder(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setType(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setTopicId(cursor.getString(offset + 3));
        entity.setGameId(cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TopicToGame entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TopicToGame entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "topicToGameList" to-many relationship of GameTopicInfo. */
    public List<TopicToGame> _queryGameTopicInfo_TopicToGameList(String topicId) {
        synchronized (this) {
            if (gameTopicInfo_TopicToGameListQuery == null) {
                QueryBuilder<TopicToGame> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.TopicId.eq(null));
                queryBuilder.orderRaw("RETURN_ORDER ASC");
                gameTopicInfo_TopicToGameListQuery = queryBuilder.build();
            }
        }
        Query<TopicToGame> query = gameTopicInfo_TopicToGameListQuery.forCurrentThread();
        query.setParameter(0, topicId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getGameTopicInfoDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getGameInfoDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getThirdGameInfoDao().getAllColumns());
            builder.append(" FROM TOPIC_TO_GAME T");
            builder.append(" LEFT JOIN GAME_TOPIC_INFO T0 ON T.'TOPIC_ID'=T0.'TOPIC_ID'");
            builder.append(" LEFT JOIN GAME_INFO T1 ON T.'GAME_ID'=T1.'GAME_ID'");
            builder.append(" LEFT JOIN THIRD_GAME_INFO T2 ON T.'GAME_ID'=T2.'GAME_ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected TopicToGame loadCurrentDeep(Cursor cursor, boolean lock) {
        TopicToGame entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        GameTopicInfo gameTopicInfo = loadCurrentOther(daoSession.getGameTopicInfoDao(), cursor, offset);
         if(gameTopicInfo != null) {
            entity.setGameTopicInfo(gameTopicInfo);
        }
        offset += daoSession.getGameTopicInfoDao().getAllColumns().length;

        GameInfo gameInfo = loadCurrentOther(daoSession.getGameInfoDao(), cursor, offset);
         if(gameInfo != null) {
            entity.setGameInfo(gameInfo);
        }
        offset += daoSession.getGameInfoDao().getAllColumns().length;

        ThirdGameInfo thirdGameInfo = loadCurrentOther(daoSession.getThirdGameInfoDao(), cursor, offset);
         if(thirdGameInfo != null) {
            entity.setThirdGameInfo(thirdGameInfo);
        }

        return entity;    
    }

    public TopicToGame loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<TopicToGame> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<TopicToGame> list = new ArrayList<TopicToGame>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<TopicToGame> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<TopicToGame> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
