package com.atet.tvmarket.entity.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.atet.tvmarket.entity.dao.UpdateInterfaceInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table UPDATE_INTERFACE_INFO.
*/
public class UpdateInterfaceInfoDao extends AbstractDao<UpdateInterfaceInfo, String> {

    public static final String TABLENAME = "UPDATE_INTERFACE_INFO";

    /**
     * Properties of entity UpdateInterfaceInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property UniqueId = new Property(0, String.class, "uniqueId", true, "UNIQUE_ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property SubId = new Property(2, String.class, "subId", false, "SUB_ID");
        public final static Property UpdateTime = new Property(3, Long.class, "updateTime", false, "UPDATE_TIME");
    };

    private DaoSession daoSession;


    public UpdateInterfaceInfoDao(DaoConfig config) {
        super(config);
    }
    
    public UpdateInterfaceInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'UPDATE_INTERFACE_INFO' (" + //
                "'UNIQUE_ID' TEXT PRIMARY KEY NOT NULL ," + // 0: uniqueId
                "'NAME' TEXT," + // 1: name
                "'SUB_ID' TEXT," + // 2: subId
                "'UPDATE_TIME' INTEGER);"); // 3: updateTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'UPDATE_INTERFACE_INFO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, UpdateInterfaceInfo entity) {
        stmt.clearBindings();
 
        String uniqueId = entity.getUniqueId();
        if (uniqueId != null) {
            stmt.bindString(1, uniqueId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String subId = entity.getSubId();
        if (subId != null) {
            stmt.bindString(3, subId);
        }
 
        Long updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindLong(4, updateTime);
        }
    }

    @Override
    protected void attachEntity(UpdateInterfaceInfo entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public UpdateInterfaceInfo readEntity(Cursor cursor, int offset) {
        UpdateInterfaceInfo entity = new UpdateInterfaceInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // uniqueId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // subId
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // updateTime
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, UpdateInterfaceInfo entity, int offset) {
        entity.setUniqueId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSubId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUpdateTime(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(UpdateInterfaceInfo entity, long rowId) {
        return entity.getUniqueId();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(UpdateInterfaceInfo entity) {
        if(entity != null) {
            return entity.getUniqueId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getLocalUpdateInfoDao().getAllColumns());
            builder.append(" FROM UPDATE_INTERFACE_INFO T");
            builder.append(" LEFT JOIN LOCAL_UPDATE_INFO T0 ON T.'UNIQUE_ID'=T0.'LOCAL_UNIQUE_ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected UpdateInterfaceInfo loadCurrentDeep(Cursor cursor, boolean lock) {
        UpdateInterfaceInfo entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        LocalUpdateInfo localUpdateInfo = loadCurrentOther(daoSession.getLocalUpdateInfoDao(), cursor, offset);
        entity.setLocalUpdateInfo(localUpdateInfo);

        return entity;    
    }

    public UpdateInterfaceInfo loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<UpdateInterfaceInfo> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<UpdateInterfaceInfo> list = new ArrayList<UpdateInterfaceInfo>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<UpdateInterfaceInfo> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<UpdateInterfaceInfo> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
