package com.atet.tvmarket.entity.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table USER_GIFT_INFO.
 */
public class UserGiftInfo implements java.io.Serializable {

    private String giftPackageid;
    private String giftCode;
    private String icon;
    private String name;
    private String gameName;
    private String gameId;
    private String content;
    private String useMethod;
    private Long receiveTime;

    // KEEP FIELDS - put your custom fields here
	private static final long serialVersionUID = 1L;
    // KEEP FIELDS END

    public UserGiftInfo() {
    }

    public UserGiftInfo(String giftPackageid) {
        this.giftPackageid = giftPackageid;
    }

    public UserGiftInfo(String giftPackageid, String giftCode, String icon, String name, String gameName, String gameId, String content, String useMethod, Long receiveTime) {
        this.giftPackageid = giftPackageid;
        this.giftCode = giftCode;
        this.icon = icon;
        this.name = name;
        this.gameName = gameName;
        this.gameId = gameId;
        this.content = content;
        this.useMethod = useMethod;
        this.receiveTime = receiveTime;
    }

    public String getGiftPackageid() {
        return giftPackageid;
    }

    public void setGiftPackageid(String giftPackageid) {
        this.giftPackageid = giftPackageid;
    }

    public String getGiftCode() {
        return giftCode;
    }

    public void setGiftCode(String giftCode) {
        this.giftCode = giftCode;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getGameName() {
        return gameName;
    }

    public void setGameName(String gameName) {
        this.gameName = gameName;
    }

    public String getGameId() {
        return gameId;
    }

    public void setGameId(String gameId) {
        this.gameId = gameId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getUseMethod() {
        return useMethod;
    }

    public void setUseMethod(String useMethod) {
        this.useMethod = useMethod;
    }

    public Long getReceiveTime() {
        return receiveTime;
    }

    public void setReceiveTime(Long receiveTime) {
        this.receiveTime = receiveTime;
    }

    // KEEP METHODS - put your custom methods here
	@Override
	public String toString() {
		return "UserGiftInfo [giftPackageid=" + giftPackageid + ", giftCode="
				+ giftCode + ", icon=" + icon + ", name=" + name
				+ ", gameName=" + gameName + ", gameId=" + gameId
				+ ", content=" + content + ", useMethod=" + useMethod
				+ ", receiveTime=" + receiveTime + "]";
	}
    // KEEP METHODS END

}
