package com.atet.tvmarket.entity.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.atet.tvmarket.entity.dao.UserGameGiftInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table USER_GAME_GIFT_INFO.
*/
public class UserGameGiftInfoDao extends AbstractDao<UserGameGiftInfo, String> {

    public static final String TABLENAME = "USER_GAME_GIFT_INFO";

    /**
     * Properties of entity UserGameGiftInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Gameid = new Property(0, String.class, "gameid", true, "GAMEID");
        public final static Property GameName = new Property(1, String.class, "gameName", false, "GAME_NAME");
        public final static Property MinPhoto = new Property(2, String.class, "minPhoto", false, "MIN_PHOTO");
    };

    private DaoSession daoSession;


    public UserGameGiftInfoDao(DaoConfig config) {
        super(config);
    }
    
    public UserGameGiftInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'USER_GAME_GIFT_INFO' (" + //
                "'GAMEID' TEXT PRIMARY KEY NOT NULL ," + // 0: gameid
                "'GAME_NAME' TEXT," + // 1: gameName
                "'MIN_PHOTO' TEXT);"); // 2: minPhoto
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'USER_GAME_GIFT_INFO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, UserGameGiftInfo entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getGameid());
 
        String gameName = entity.getGameName();
        if (gameName != null) {
            stmt.bindString(2, gameName);
        }
 
        String minPhoto = entity.getMinPhoto();
        if (minPhoto != null) {
            stmt.bindString(3, minPhoto);
        }
    }

    @Override
    protected void attachEntity(UserGameGiftInfo entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public UserGameGiftInfo readEntity(Cursor cursor, int offset) {
        UserGameGiftInfo entity = new UserGameGiftInfo( //
            cursor.getString(offset + 0), // gameid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // gameName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // minPhoto
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, UserGameGiftInfo entity, int offset) {
        entity.setGameid(cursor.getString(offset + 0));
        entity.setGameName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMinPhoto(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(UserGameGiftInfo entity, long rowId) {
        return entity.getGameid();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(UserGameGiftInfo entity) {
        if(entity != null) {
            return entity.getGameid();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
