package com.atet.tvmarket.entity.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.atet.tvmarket.entity.dao.UserGameToGift;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table USER_GAME_TO_GIFT.
*/
public class UserGameToGiftDao extends AbstractDao<UserGameToGift, Long> {

    public static final String TABLENAME = "USER_GAME_TO_GIFT";

    /**
     * Properties of entity UserGameToGift.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ReturnOrder = new Property(1, Integer.class, "returnOrder", false, "RETURN_ORDER");
        public final static Property GameId = new Property(2, String.class, "gameId", false, "GAME_ID");
        public final static Property GiftPackageid = new Property(3, String.class, "giftPackageid", false, "GIFT_PACKAGEID");
        public final static Property UserId = new Property(4, String.class, "userId", false, "USER_ID");
    };

    private DaoSession daoSession;

    private Query<UserGameToGift> userGameGiftInfo_UserGameToGiftListQuery;

    public UserGameToGiftDao(DaoConfig config) {
        super(config);
    }
    
    public UserGameToGiftDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'USER_GAME_TO_GIFT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'RETURN_ORDER' INTEGER," + // 1: returnOrder
                "'GAME_ID' TEXT NOT NULL ," + // 2: gameId
                "'GIFT_PACKAGEID' TEXT NOT NULL ," + // 3: giftPackageid
                "'USER_ID' TEXT NOT NULL );"); // 4: userId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'USER_GAME_TO_GIFT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, UserGameToGift entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer returnOrder = entity.getReturnOrder();
        if (returnOrder != null) {
            stmt.bindLong(2, returnOrder);
        }
        stmt.bindString(3, entity.getGameId());
        stmt.bindString(4, entity.getGiftPackageid());
        stmt.bindString(5, entity.getUserId());
    }

    @Override
    protected void attachEntity(UserGameToGift entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public UserGameToGift readEntity(Cursor cursor, int offset) {
        UserGameToGift entity = new UserGameToGift( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // returnOrder
            cursor.getString(offset + 2), // gameId
            cursor.getString(offset + 3), // giftPackageid
            cursor.getString(offset + 4) // userId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, UserGameToGift entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setReturnOrder(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setGameId(cursor.getString(offset + 2));
        entity.setGiftPackageid(cursor.getString(offset + 3));
        entity.setUserId(cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(UserGameToGift entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(UserGameToGift entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "userGameToGiftList" to-many relationship of UserGameGiftInfo. */
    public List<UserGameToGift> _queryUserGameGiftInfo_UserGameToGiftList(String gameId) {
        synchronized (this) {
            if (userGameGiftInfo_UserGameToGiftListQuery == null) {
                QueryBuilder<UserGameToGift> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.GameId.eq(null));
                queryBuilder.orderRaw("RETURN_ORDER ASC");
                userGameGiftInfo_UserGameToGiftListQuery = queryBuilder.build();
            }
        }
        Query<UserGameToGift> query = userGameGiftInfo_UserGameToGiftListQuery.forCurrentThread();
        query.setParameter(0, gameId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUserGiftInfoDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getUserGameGiftInfoDao().getAllColumns());
            builder.append(" FROM USER_GAME_TO_GIFT T");
            builder.append(" LEFT JOIN USER_GIFT_INFO T0 ON T.'GIFT_PACKAGEID'=T0.'GIFT_PACKAGEID'");
            builder.append(" LEFT JOIN USER_GAME_GIFT_INFO T1 ON T.'GAME_ID'=T1.'GAMEID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected UserGameToGift loadCurrentDeep(Cursor cursor, boolean lock) {
        UserGameToGift entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        UserGiftInfo userGiftInfo = loadCurrentOther(daoSession.getUserGiftInfoDao(), cursor, offset);
         if(userGiftInfo != null) {
            entity.setUserGiftInfo(userGiftInfo);
        }
        offset += daoSession.getUserGiftInfoDao().getAllColumns().length;

        UserGameGiftInfo userGameGiftInfo = loadCurrentOther(daoSession.getUserGameGiftInfoDao(), cursor, offset);
         if(userGameGiftInfo != null) {
            entity.setUserGameGiftInfo(userGameGiftInfo);
        }

        return entity;    
    }

    public UserGameToGift loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<UserGameToGift> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<UserGameToGift> list = new ArrayList<UserGameToGift>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<UserGameToGift> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<UserGameToGift> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
