package com.atet.tvmarket.entity.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table USER_TASK_RECORD.
 */
public class UserTaskRecord implements java.io.Serializable {

    private Long id;
    private String type;
    private Integer userId;
    private String gameId;
    private Long time;
    private String str1;
    private String str2;
    private Integer int1;
    private Integer int2;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public UserTaskRecord() {
    }

    public UserTaskRecord(Long id) {
        this.id = id;
    }

    public UserTaskRecord(Long id, String type, Integer userId, String gameId, Long time, String str1, String str2, Integer int1, Integer int2) {
        this.id = id;
        this.type = type;
        this.userId = userId;
        this.gameId = gameId;
        this.time = time;
        this.str1 = str1;
        this.str2 = str2;
        this.int1 = int1;
        this.int2 = int2;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getGameId() {
        return gameId;
    }

    public void setGameId(String gameId) {
        this.gameId = gameId;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public String getStr1() {
        return str1;
    }

    public void setStr1(String str1) {
        this.str1 = str1;
    }

    public String getStr2() {
        return str2;
    }

    public void setStr2(String str2) {
        this.str2 = str2;
    }

    public Integer getInt1() {
        return int1;
    }

    public void setInt1(Integer int1) {
        this.int1 = int1;
    }

    public Integer getInt2() {
        return int2;
    }

    public void setInt2(Integer int2) {
        this.int2 = int2;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
