package com.atet.tvmarket.entity.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table VIDEO_INFO.
 */
public class VideoInfo implements java.io.Serializable {

    private Long id;
    private String videoName;
    private String videoUrl;
    private String videoIcon;
    private String videoBgIcon;
    private String videoRemark;
    private String videoType;

    // KEEP FIELDS - put your custom fields here
	private static final long serialVersionUID = 1L;
    // KEEP FIELDS END

    public VideoInfo() {
    }

    public VideoInfo(Long id) {
        this.id = id;
    }

    public VideoInfo(Long id, String videoName, String videoUrl, String videoIcon, String videoBgIcon, String videoRemark, String videoType) {
        this.id = id;
        this.videoName = videoName;
        this.videoUrl = videoUrl;
        this.videoIcon = videoIcon;
        this.videoBgIcon = videoBgIcon;
        this.videoRemark = videoRemark;
        this.videoType = videoType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getVideoName() {
        return videoName;
    }

    public void setVideoName(String videoName) {
        this.videoName = videoName;
    }

    public String getVideoUrl() {
        return videoUrl;
    }

    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }

    public String getVideoIcon() {
        return videoIcon;
    }

    public void setVideoIcon(String videoIcon) {
        this.videoIcon = videoIcon;
    }

    public String getVideoBgIcon() {
        return videoBgIcon;
    }

    public void setVideoBgIcon(String videoBgIcon) {
        this.videoBgIcon = videoBgIcon;
    }

    public String getVideoRemark() {
        return videoRemark;
    }

    public void setVideoRemark(String videoRemark) {
        this.videoRemark = videoRemark;
    }

    public String getVideoType() {
        return videoType;
    }

    public void setVideoType(String videoType) {
        this.videoType = videoType;
    }

    // KEEP METHODS - put your custom methods here
	@Override
	public String toString() {
		return "VideoInfo [id=" + id + ", videoName=" + videoName
				+ ", videoUrl=" + videoUrl + ", videoIcon=" + videoIcon
				+ ", videoBgIcon=" + videoBgIcon + ", videoRemark="
				+ videoRemark + ", videoType=" + videoType + "]";
	}
    // KEEP METHODS END

}
